/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        cream: '#f4ead9',
        'deep-brown': '#241a13',
        'deep-brown-dark': '#1a120d',
        'dark-text': '#2c2016',
        'dark-text-secondary': '#4a3c2c',
        gold: '#b98a3e',
        'gold-light': '#d1a55e',
        'muted-green': '#445c3c',
        'cream-accent': '#e9dcc4',
        'brown-light': '#c9b998',
        'brown-lighter': '#cbb99a',
        'brown-muted': '#6b5c48',
        'brown-pale': '#8a7a63',
        'brown-dull': '#a8977c',
        'black': '#241a13',
      },
      fontFamily: {
        serif: ['EB Garamond', 'serif'],
        sans: ['Work Sans', 'sans-serif'],
      },
      spacing: {
        '0.375': '0.375rem',
        '0.75': '0.75rem',
        '1.5': '1.5rem',
        '2': '2rem',
        '2.5': '2.5rem',
        '3': '3rem',
        '3.5': '3.5rem',
        '3.75': '3.75rem',
        '4': '4rem',
        '4.25': '4.25rem',
        '4.5': '4.5rem',
        '6': '6rem',
        '7': '7rem',
        '8': '8rem',
        '9': '9rem',
        '9.5': '9.5rem',
        '11': '11rem',
        '12': '12rem',
        '13': '13rem',
        '14': '14rem',
        '16': '16rem',
        '20': '20rem',
        '30': '30rem',
      },
      fontSize: {
        'xs': ['12px', { lineHeight: '1.4' }],
        'sm': ['14px', { lineHeight: '1.5' }],
        'base': ['16px', { lineHeight: '1.6' }],
        'lg': ['18px', { lineHeight: '1.7' }],
        'xl': ['20px', { lineHeight: '1.8' }],
        '2xl': ['22px', { lineHeight: '1.8' }],
        '3xl': ['26px', { lineHeight: '1.8' }],
        '4xl': ['30px', { lineHeight: '1.8' }],
      },
    },
  },
  plugins: [],
};
